In [1]:
from sklearn.preprocessing import LabelEncoder, OrdinalEncoder, OneHotEncoder

import pandas as pd
import numpy as np

In [2]:
np.random.seed(123)
df = pd.DataFrame({'feature 1': np.random.normal(10, 1.5, 20),
             'feature 2': np.random.choice(['dog', 'cat', 'lion'], size=20, p=[0.3, 0.3, 0.4])
             })

In [15]:
df.head(10)

feature 1 feature 2
0   8.371554      lion
1  11.496018      lion
2  10.424468      lion
3   7.740558       cat
4   9.132100       cat
5  12.477155       dog
6   6.359981       dog
7   9.356631      lion
8  11.898904       dog
9   8.699889       cat

In [19]:
encoder1 = LabelEncoder()

In [20]:
encoder1.fit_transform(df['feature 2'])

array([2, 2, 2, 0, 0, 1, 1, 2, 1, 0, 0, 0, 0, 0, 0, 2, 2, 0, 2, 1])

# Ordinal Encoder

In [21]:
encoder2 = OrdinalEncoder()

In [23]:
encoder2.fit_transform(np.array(df['feature 2']).reshape(-1, 1))

array([[2.],
       [2.],
       [2.],
       [0.],
       [0.],
       [1.],
       [1.],
       [2.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [2.],
       [2.],
       [0.],
       [2.],
       [1.]])

# One Hot Encoder

In [3]:
encoder3 = OneHotEncoder()

In [4]:
result = encoder3.fit_transform(np.array(df['feature 2']).reshape(-1, 1))

In [9]:
encoder3.categories_

[array(['cat', 'dog', 'lion'], dtype=object)]

In [5]:
result.toarray()

array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.]])